on:
  pull_request:
  push:
    branches:
      - main
name: Lint check
jobs:
  black:
    name: black check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.x
      - name: Poetry Setup
        uses: snok/install-poetry@v1.1.4
        with:
          version: 1.1.4
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: poetry install
      - uses: actions/checkout@v1
      - name: Test Code Lint
        run: |
          make check
